services:
  gpio-app:
    build: .
    container_name: carwash-app
    ports:
      - "8888:8888"  # Map the pigpiod port
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # Access to GPIO memory
    cap_add:
      - SYS_RAWIO  # Allows direct GPIO access
    environment:
      - PIGPIO_ADDR=host.docker.internal  # Connect to host pigpiod
      - PIGPIO_PORT=8888
    restart: unless-stopped