name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker-compose build

      # Step 4: Run the tests in the Docker container
      - name: Run Unit Tests
        run: docker-compose run --rm carwash-touchscreen-app python -m unittest discover tests

      # Step 5: Optional - Upload test reports (if you have any)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/