name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker compose build

      # Step 4: Run the tests in the Docker container
      - name: Run Unit Tests
        run: docker compose run --rm carwash-touchscreen-app python -m unittest discover tests

      # Step 5: Optional - Upload test reports (if you have any)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Determine Docker image tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "tag=develop" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.tag }} .

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.tag }}