# .github/workflows/python-linter.yml

name: Python Linter

on:
  push:
    branches:
      - develop  # Runs the action only on pushes to the develop branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install flake8 or another linter if you prefer

      - name: Run flake8
        run: |
          flake8 .  # Run flake8 on the entire repository